### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JanMarvin** [hadley/exell#3]
libxls is BSD-licensed. So exell must be BSD-licensed as well if libxls is included.

Minor note: How does that work with Rcpp? Can a Rcpp package have a different license than GPL? With MIT I assume its  okay, but with BSD?

**Comment by JanMarvin** [comment]
Oh wait sry, its BSD 2-clause. Acording to FSF thats okay. My bad.
:)

**Comment by hadley** [comment]
I think you're getting confused - if libxls was GPL licensed, exell would also need to be GPL licensed. But BSD isn't "infectious" in the same way.

**Comment by JanMarvin** [comment]
Yes, newer BSD isn't. Older 4-clause BSD was incompatible with GPL due to the advertising clause. Therefore I assumed a license mixup. Nervermind, everythings fine.
